"""modif_notifications

Revision ID: 7e2ca4f17831
Revises: 57d533765958
Create Date: 2021-07-27 15:05:41.156637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2ca4f17831'
down_revision = '57d533765958'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operateur', sa.Column('last_notemaj_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operateur', 'last_notemaj_id')
    # ### end Alembic commands ###
