"""affaire_attribution

Revision ID: 72499d23d034
Revises: b8e660727760
Create Date: 2021-10-27 15:12:22.123281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72499d23d034'
down_revision = 'b8e660727760'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affaire', sa.Column('attribution', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affaire', 'attribution')
    # ### end Alembic commands ###
