"""update ctrl_geom

Revision ID: 13fcb71e77c1
Revises: 5a8069c68433
Create Date: 2021-09-09 17:05:14.208648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fcb71e77c1'
down_revision = '5a8069c68433'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controle_geometre', sa.Column('check_48', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_49', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_50', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_51', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_52', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_53', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_54', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_55', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_56', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_57', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_58', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_59', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_60', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_61', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_62', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_63', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_64', sa.Boolean(), nullable=True))
    op.add_column('controle_geometre', sa.Column('check_65', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controle_geometre', 'check_65')
    op.drop_column('controle_geometre', 'check_64')
    op.drop_column('controle_geometre', 'check_63')
    op.drop_column('controle_geometre', 'check_62')
    op.drop_column('controle_geometre', 'check_61')
    op.drop_column('controle_geometre', 'check_60')
    op.drop_column('controle_geometre', 'check_59')
    op.drop_column('controle_geometre', 'check_58')
    op.drop_column('controle_geometre', 'check_57')
    op.drop_column('controle_geometre', 'check_56')
    op.drop_column('controle_geometre', 'check_55')
    op.drop_column('controle_geometre', 'check_54')
    op.drop_column('controle_geometre', 'check_53')
    op.drop_column('controle_geometre', 'check_52')
    op.drop_column('controle_geometre', 'check_51')
    op.drop_column('controle_geometre', 'check_50')
    op.drop_column('controle_geometre', 'check_49')
    op.drop_column('controle_geometre', 'check_48')
    # ### end Alembic commands ###
