"""Ajout role_id

Revision ID: f013078b6c2f
Revises: b8e660727760
Create Date: 2021-10-27 16:21:54.865115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f013078b6c2f'
down_revision = 'b8e660727760'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ### 
    op.add_column('operateur', sa.Column('role_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_operateur_role_id_role'), 'operateur', 'role', ['role_id'], ['id'], source_schema='infolica', referent_schema='infolica')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_operateur_role_id_role'), 'operateur', schema='infolica', type_='foreignkey')
    op.drop_column('operateur', 'role_id')
    # ### end Alembic commands ###
