"""notes_maj_update

Revision ID: fce39ef8499e
Revises: fa78303f6939
Create Date: 2021-07-27 15:32:12.931067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce39ef8499e'
down_revision = 'fa78303f6939'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operateur', sa.Column('last_notemaj_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operateur', 'last_notemaj_id')
    # ### end Alembic commands ###
