"""affaire urgente

Revision ID: cd2fb3237edb
Revises: aefafb13d2ce
Create Date: 2021-07-06 07:59:29.055430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2fb3237edb'
down_revision = 'aefafb13d2ce'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affaire', sa.Column('urgent', sa.Boolean(), nullable=True))
    op.add_column('affaire', sa.Column('urgent_echeance', sa.Date(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affaire', 'urgent_echeance')
    op.drop_column('affaire', 'urgent')
    # ### end Alembic commands ###
