"""ajouter le champ ldap domain pour les operateurs

Revision ID: f9b610b87b94
Revises: bb9331cedec2
Create Date: 2022-07-11 13:23:41.890678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b610b87b94'
down_revision = 'bb9331cedec2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operateur', sa.Column('ldap_domain', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operateur', 'ldap_domain')
    # ### end Alembic commands ###
