"""preavis

Revision ID: 329d624ca6ba
Revises: 3a2d967c76fc
Create Date: 2022-03-11 15:21:57.444614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329d624ca6ba'
down_revision = '3a2d967c76fc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preavis_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('preavis_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('filetype', sa.Text(), nullable=False),
    sa.Column('filesize_ko', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['preavis_id'], ['infolica.preavis.id'], name=op.f('fk_preavis_documents_preavis_id_preavis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preavis_documents')),
    schema='infolica'
    )
    op.create_table('remarque_preavis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('preavis_id', sa.BigInteger(), nullable=False),
    sa.Column('remarque', sa.Text(), nullable=False),
    sa.Column('operateur_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['operateur_id'], ['infolica.operateur.id'], name=op.f('fk_remarque_preavis_operateur_id_operateur')),
    sa.ForeignKeyConstraint(['preavis_id'], ['infolica.preavis.id'], name=op.f('fk_remarque_preavis_preavis_id_preavis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remarque_preavis')),
    schema='infolica'
    )
    op.add_column('operateur', sa.Column('service', sa.Text(), nullable=True))
    op.add_column('operateur', sa.Column('service_id', sa.BigInteger(), nullable=True))
    op.add_column('preavis', sa.Column('operateur_sgrf_id', sa.BigInteger(), nullable=True))
    op.add_column('preavis', sa.Column('operateur_service_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preavis', 'operateur_service_id')
    op.drop_column('preavis', 'operateur_sgrf_id')
    op.drop_column('operateur', 'service_id')
    op.drop_column('operateur', 'service')
    op.drop_table('remarque_preavis', schema='infolica')
    op.drop_table('preavis_documents', schema='infolica')
    # ### end Alembic commands ###
