"""adapt period outside sgrf in table affaire_etape

Revision ID: 894e95223b77
Revises: c953f0839dae
Create Date: 2022-10-21 17:16:46.561863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894e95223b77'
down_revision = 'c953f0839dae'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affaire_etape', sa.Column('hors_sgrf_de', sa.Date(), nullable=True))
    op.add_column('affaire_etape', sa.Column('hors_sgrf_a', sa.Date(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affaire_etape', 'hors_sgrf_a')
    op.drop_column('affaire_etape', 'hors_sgrf_de')
    # ### end Alembic commands ###
