"""preavis

Revision ID: 2da31dd15873
Revises: 3a2d967c76fc
Create Date: 2022-03-31 08:57:44.868796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da31dd15873'
down_revision = '3a2d967c76fc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preavis_decision',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('preavis_id', sa.BigInteger(), nullable=False),
    sa.Column('preavis_type_id', sa.BigInteger(), nullable=True),
    sa.Column('operateur_service_id', sa.BigInteger(), nullable=True),
    sa.Column('remarque', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('definitif', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operateur_service_id'], ['infolica.operateur.id'], name=op.f('fk_preavis_decision_operateur_service_id_operateur')),
    sa.ForeignKeyConstraint(['preavis_id'], ['infolica.preavis.id'], name=op.f('fk_preavis_decision_preavis_id_preavis')),
    sa.ForeignKeyConstraint(['preavis_type_id'], ['infolica.preavis_type.id'], name=op.f('fk_preavis_decision_preavis_type_id_preavis_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preavis_decision')),
    schema='infolica'
    )
    op.create_table('preavis_remarque',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('preavis_id', sa.BigInteger(), nullable=False),
    sa.Column('remarque', sa.Text(), nullable=False),
    sa.Column('operateur_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['operateur_id'], ['infolica.operateur.id'], name=op.f('fk_preavis_remarque_operateur_id_operateur')),
    sa.ForeignKeyConstraint(['preavis_id'], ['infolica.preavis.id'], name=op.f('fk_preavis_remarque_preavis_id_preavis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preavis_remarque')),
    schema='infolica'
    )
    op.add_column('operateur', sa.Column('service', sa.Text(), nullable=True))
    op.add_column('operateur', sa.Column('service_id', sa.BigInteger(), nullable=True))
    op.add_column('preavis', sa.Column('operateur_sgrf_id', sa.BigInteger(), nullable=True))
    op.add_column('preavis', sa.Column('operateur_service_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preavis', 'operateur_service_id')
    op.drop_column('preavis', 'operateur_sgrf_id')
    op.drop_column('operateur', 'service_id')
    op.drop_column('operateur', 'service')
    op.drop_table('preavis_remarque', schema='infolica')
    op.drop_table('preavis_decision', schema='infolica')
    # ### end Alembic commands ###
