"""update ctrl suivi_mandat with MPD

Revision ID: efd033d9fa0a
Revises: 74b698ab82b0
Create Date: 2022-02-11 09:24:23.427741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd033d9fa0a'
down_revision = '74b698ab82b0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suivi_mandat', sa.Column('gen_pdf_travaux', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suivi_mandat', sa.Column('geos_couleur_pastilles', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suivi_mandat', sa.Column('normes_respect_petits_objects', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suivi_mandat', sa.Column('normes_bat_couv_digitalises', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suivi_mandat', sa.Column('gen_geoportail_attributs', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suivi_mandat', sa.Column('gen_scan_croquis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suivi_mandat', 'gen_scan_croquis')
    op.drop_column('suivi_mandat', 'gen_geoportail_attributs')
    op.drop_column('suivi_mandat', 'normes_bat_couv_digitalises')
    op.drop_column('suivi_mandat', 'normes_respect_petits_objects')
    op.drop_column('suivi_mandat', 'geos_couleur_pastilles')
    op.drop_column('suivi_mandat', 'gen_pdf_travaux')
    # ### end Alembic commands ###
