"""update ctrl coordinateur

Revision ID: 39c23d05e085
Revises: f9b610b87b94
Create Date: 2022-07-05 10:28:12.964901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c23d05e085'
down_revision = 'f9b610b87b94'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suivi_mandat', sa.Column('pfp3_ctrl_calcul', sa.Boolean(), nullable=True))
    op.add_column('suivi_mandat', sa.Column('pfp3_ctrl_fiabilite', sa.Boolean(), nullable=True))
    op.add_column('suivi_mandat', sa.Column('pfp3_ctrl_coordonnees_geomedia_ltop', sa.Boolean(), nullable=True))
    op.add_column('suivi_mandat', sa.Column('pfp3_protection_symbole_geomedia', sa.Boolean(), nullable=True))
    op.add_column('suivi_mandat', sa.Column('fact_forfait', sa.Boolean(), nullable=True))
    op.add_column('suivi_mandat', sa.Column('fact_lettre_accompagnement', sa.Boolean(), nullable=True))
    op.add_column('suivi_mandat', sa.Column('fact_tva', sa.Boolean(), nullable=True))
    op.add_column('suivi_mandat', sa.Column('documents_complets', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suivi_mandat', 'documents_complets')
    op.drop_column('suivi_mandat', 'fact_tva')
    op.drop_column('suivi_mandat', 'fact_lettre_accompagnement')
    op.drop_column('suivi_mandat', 'fact_forfait')
    op.drop_column('suivi_mandat', 'pfp3_protection_symbole_geomedia')
    op.drop_column('suivi_mandat', 'pfp3_ctrl_coordonnees_geomedia_ltop')
    op.drop_column('suivi_mandat', 'pfp3_ctrl_fiabilite')
    op.drop_column('suivi_mandat', 'pfp3_ctrl_calcul')
    # ### end Alembic commands ###
