"""add service_amenagement_territoire_id to cadastre

Revision ID: 39d1b5c44dee
Revises: a4997f372346
Create Date: 2022-05-30 11:22:03.607542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d1b5c44dee'
down_revision = 'a4997f372346'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cadastre', sa.Column('service_at_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cadastre', 'service_at_id')
    # ### end Alembic commands ###
