"""update ctrl coord projets

Revision ID: d6c830d7fbfb
Revises: 894e95223b77
Create Date: 2022-10-27 10:28:24.241985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c830d7fbfb'
down_revision = '894e95223b77'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suivi_mandat', sa.Column('fact_adresse_correcte', sa.Boolean(), nullable=True))
    op.add_column('suivi_mandat', sa.Column('fact_coordination_cdf_ne', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suivi_mandat', 'fact_coordination_cdf_ne')
    op.drop_column('suivi_mandat', 'fact_adresse_correcte')
    # ### end Alembic commands ###
