"""retarder validation geomedia

Revision ID: 583faa835866
Revises: 39c23d05e085
Create Date: 2022-09-16 09:01:43.402712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583faa835866'
down_revision = '39c23d05e085'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suivi_mandat', sa.Column('geos_retarder_validation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suivi_mandat', 'geos_retarder_validation')
    # ### end Alembic commands ###
