"""update ctrl table with specific ctrl from MPD

Revision ID: 38b66991e634
Revises: 885cb35e6d8e
Create Date: 2023-03-03 08:35:58.171188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b66991e634'
down_revision = '885cb35e6d8e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controle_mutation', sa.Column('gen_1', sa.Boolean(), nullable=True))
    op.add_column('controle_mutation', sa.Column('gen_2', sa.Boolean(), nullable=True))
    op.add_column('controle_mutation', sa.Column('gen_3', sa.Boolean(), nullable=True))
    op.add_column('controle_mutation', sa.Column('gen_4', sa.Boolean(), nullable=True))
    op.add_column('controle_mutation', sa.Column('cs_6', sa.Boolean(), nullable=True))
    op.add_column('controle_mutation', sa.Column('cs_7', sa.Boolean(), nullable=True))
    op.add_column('controle_mutation', sa.Column('cs_8', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controle_mutation', 'cs_8')
    op.drop_column('controle_mutation', 'cs_7')
    op.drop_column('controle_mutation', 'cs_6')
    op.drop_column('controle_mutation', 'gen_4')
    op.drop_column('controle_mutation', 'gen_3')
    op.drop_column('controle_mutation', 'gen_2')
    op.drop_column('controle_mutation', 'gen_1')
    # ### end Alembic commands ###
