"""update preavis formulaire decision

Revision ID: 3a451b565980
Revises: 4f5057ef6dd2
Create Date: 2023-03-21 12:00:58.619347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a451b565980'
down_revision = '4f5057ef6dd2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preavis_decision', sa.Column('remarque_contexte', sa.Text(), nullable=True))
    op.add_column('preavis_decision', sa.Column('remarque_limite_fictive_gabarits', sa.Text(), nullable=True))
    op.add_column('preavis_decision', sa.Column('remarque_transfert_droit_batir', sa.Text(), nullable=True))
    op.add_column('preavis_decision', sa.Column('remarque_stationnement_art29', sa.Text(), nullable=True))
    op.add_column('preavis_decision', sa.Column('remarque_autre', sa.Text(), nullable=True))
    op.add_column('preavis_glossaire', sa.Column('chapitre', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preavis_glossaire', 'chapitre')
    op.drop_column('preavis_decision', 'remarque_autre')
    op.drop_column('preavis_decision', 'remarque_stationnement_art29')
    op.drop_column('preavis_decision', 'remarque_transfert_droit_batir')
    op.drop_column('preavis_decision', 'remarque_limite_fictive_gabarits')
    op.drop_column('preavis_decision', 'remarque_contexte')
    # ### end Alembic commands ###
