"""update tableau_emoluments

Revision ID: 4f5057ef6dd2
Revises: 38b66991e634
Create Date: 2023-03-13 07:46:34.782070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5057ef6dd2'
down_revision = '38b66991e634'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tableau_emoluments', sa.Column('ordre', sa.Integer(), nullable=True))
    op.add_column('tableau_emoluments', sa.Column('id_hmtl', sa.Text(), nullable=True))
    op.add_column('tableau_emoluments', sa.Column('batiment', sa.Boolean(), nullable=True))
    op.add_column('tableau_emoluments', sa.Column('bien_fonds', sa.Boolean(), nullable=True))
    op.add_column('tableau_emoluments', sa.Column('code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tableau_emoluments', 'code')
    op.drop_column('tableau_emoluments', 'bien_fonds')
    op.drop_column('tableau_emoluments', 'batiment')
    op.drop_column('tableau_emoluments', 'id_hmtl')
    op.drop_column('tableau_emoluments', 'ordre')
    # ### end Alembic commands ###
