"""add item into ctrlMutation

Revision ID: 86046f932b74
Revises: 7f61c1192ef6
Create Date: 2024-05-02 15:51:01.573804

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86046f932b74"
down_revision = "7f61c1192ef6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("controle_mutation", sa.Column("cs_9", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("controle_mutation", "cs_9")
    # ### end Alembic commands ###
