"""manage service urbanisme

Revision ID: 6620a34e9d5c
Revises: 86046f932b74
Create Date: 2024-05-03 14:20:54.319033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6620a34e9d5c'
down_revision = '86046f932b74'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cadastre", "service_at_id", new_column_name="service_urbanisme_id")
    op.add_column('service', sa.Column('service_principal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cadastre", "service_urbanisme_id", new_column_name="service_at_id")
    op.drop_column('service', 'service_principal')
    # ### end Alembic commands ###
