"""add uuid field for affaires

Revision ID: 518b2bdc53d6
Revises: 6620a34e9d5c
Create Date: 2025-02-14 10:07:39.303226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518b2bdc53d6'
down_revision = '6620a34e9d5c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affaire', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.add_column('affaire', sa.Column('last_changed_uuid', sa.Date(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affaire', 'last_changed_uuid')
    op.drop_column('affaire', 'uuid')
    # ### end Alembic commands ###
