"""update client

Revision ID: 432ffd4b746d
Revises: 6620a34e9d5c
Create Date: 2025-03-27 12:03:48.861798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432ffd4b746d'
down_revision = '6620a34e9d5c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('besoin_client_facture', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'besoin_client_facture')
    # ### end Alembic commands ###
