"""init

Revision ID: 8904beb0b190
Revises: 23699963ba13
Create Date: 2019-11-19 17:00:38.326244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8904beb0b190'
down_revision = '23699963ba13'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affaire_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affaire_type'))
    )
    op.create_table('cadastre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cadastre'))
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('npa', sa.Text(), nullable=True),
    sa.Column('localite', sa.Text(), nullable=True),
    sa.Column('tel_fixe', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('entree', sa.Date(), nullable=False),
    sa.Column('sortie', sa.Date(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    op.create_table('constant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constant'))
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chemin', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_table('emoluments_mo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emoluments_mo'))
    )
    op.create_table('emoluments_mo_parametres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indice', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emoluments_mo_parametres'))
    )
    op.create_table('emoluments_rf_parametres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarif_servitude_principale', sa.Float(), nullable=False),
    sa.Column('tarif_servitude_secondaire', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emoluments_rf_parametres'))
    )
    op.create_table('modification_affaire_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modification_affaire_type'))
    )
    op.create_table('numero_etat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_numero_etat'))
    )
    op.create_table('numero_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_numero_type'))
    )
    op.create_table('operateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('prenom', sa.Text(), nullable=False),
    sa.Column('entree', sa.Date(), nullable=False),
    sa.Column('sortie', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operateur'))
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan'))
    )
    op.create_table('preavis_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preavis_decision'))
    )
    op.create_table('preavis_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preavis_type'))
    )
    op.create_table('relation_affaire_client_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relation_affaire_client_type'))
    )
    op.create_table('relation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relation_type'))
    )
    op.create_table('remarque_preavis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remarque', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remarque_preavis'))
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=True),
    sa.Column('prenom', sa.Text(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('npa', sa.Text(), nullable=True),
    sa.Column('localite', sa.Text(), nullable=True),
    sa.Column('telephone', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service'))
    )
    op.create_table('statut_affaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statut_affaire'))
    )
    op.create_table('affaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('cadastre_id', sa.Integer(), nullable=False),
    sa.Column('information', sa.Text(), nullable=True),
    sa.Column('date_ouverture', sa.Date(), nullable=False),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('localisation_E', sa.Integer(), nullable=False),
    sa.Column('localisation_N', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cadastre_id'], ['cadastre.id'], name=op.f('fk_affaire_cadastre_id_cadastre')),
    sa.ForeignKeyConstraint(['responsable_id'], ['operateur.id'], name=op.f('fk_affaire_responsable_id_operateur')),
    sa.ForeignKeyConstraint(['technicien_id'], ['operateur.id'], name=op.f('fk_affaire_technicien_id_operateur')),
    sa.ForeignKeyConstraint(['type_id'], ['affaire_type.id'], name=op.f('fk_affaire_type_id_affaire_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affaire'))
    )
    op.create_table('client_entreprise',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_client_entreprise_client_id_client'))
    )
    op.create_table('client_personne',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.Text(), nullable=True),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('prenom', sa.Text(), nullable=False),
    sa.Column('tel_portable', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_client_personne_client_id_client'))
    )
    op.create_table('envoi_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['destinataire_id'], ['client.id'], name=op.f('fk_envoi_document_destinataire_id_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_envoi_document'))
    )
    op.create_table('facture',
    sa.Column('sap', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('montant_mo', sa.Float(), nullable=False),
    sa.Column('montant_rf', sa.Float(), nullable=False),
    sa.Column('montant_mat_diff', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_facture_client_id_client')),
    sa.PrimaryKeyConstraint('sap', name=op.f('pk_facture'))
    )
    op.create_table('numero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadastre_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('suffixe', sa.Text(), nullable=True),
    sa.Column('etat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cadastre_id'], ['cadastre.id'], name=op.f('fk_numero_cadastre_id_cadastre')),
    sa.ForeignKeyConstraint(['etat_id'], ['numero_etat.id'], name=op.f('fk_numero_etat_id_numero_etat')),
    sa.ForeignKeyConstraint(['type_id'], ['numero_type.id'], name=op.f('fk_numero_type_id_numero_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_numero'))
    )
    op.create_table('remarque_affaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remarque', sa.Text(), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateur.id'], name=op.f('fk_remarque_affaire_operateur_id_operateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remarque_affaire'))
    )
    op.create_table('affaire_numero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affaire_id', sa.Integer(), nullable=False),
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.Column('modifie', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['affaire_id'], ['affaire.id'], name=op.f('fk_affaire_numero_affaire_id_affaire')),
    sa.ForeignKeyConstraint(['numero_id'], ['numero.id'], name=op.f('fk_affaire_numero_numero_id_numero')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affaire_numero'))
    )
    op.create_table('emoluments_rf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affaire_id'], ['affaire.id'], name=op.f('fk_emoluments_rf_affaire_id_affaire')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emoluments_rf'))
    )
    op.create_table('etape_affaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affaire_id', sa.Integer(), nullable=False),
    sa.Column('statut_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['affaire_id'], ['affaire.id'], name=op.f('fk_etape_affaire_affaire_id_affaire')),
    sa.ForeignKeyConstraint(['statut_id'], ['statut_affaire.id'], name=op.f('fk_etape_affaire_statut_id_statut_affaire')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etape_affaire'))
    )
    op.create_table('facture_partielle',
    sa.Column('facture_sap', sa.Integer(), nullable=True),
    sa.Column('immeuble', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['facture_sap'], ['facture.sap'], name=op.f('fk_facture_partielle_facture_sap_facture'))
    )
    op.create_table('modification_affaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affaire_id_mere', sa.Integer(), nullable=False),
    sa.Column('affaire_id_fille', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affaire_id_fille'], ['affaire.id'], name=op.f('fk_modification_affaire_affaire_id_fille_affaire')),
    sa.ForeignKeyConstraint(['affaire_id_mere'], ['affaire.id'], name=op.f('fk_modification_affaire_affaire_id_mere_affaire')),
    sa.ForeignKeyConstraint(['type_id'], ['modification_affaire_type.id'], name=op.f('fk_modification_affaire_type_id_modification_affaire_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modification_affaire'))
    )
    op.create_table('numero_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['numero_id'], ['numero.id'], name=op.f('fk_numero_plan_numero_id_numero')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_numero_plan_plan_id_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_numero_plan'))
    )
    op.create_table('numero_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_id_base', sa.Integer(), nullable=False),
    sa.Column('numero_id_associe', sa.Integer(), nullable=False),
    sa.Column('relation_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['numero_id_associe'], ['numero.id'], name=op.f('fk_numero_relation_numero_id_associe_numero')),
    sa.ForeignKeyConstraint(['numero_id_base'], ['numero.id'], name=op.f('fk_numero_relation_numero_id_base_numero')),
    sa.ForeignKeyConstraint(['relation_type_id'], ['relation_type.id'], name=op.f('fk_numero_relation_relation_type_id_relation_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_numero_relation'))
    )
    op.create_table('preavis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affaire_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('preavis_id', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('date_demande', sa.Date(), nullable=False),
    sa.Column('date_reponse', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['affaire_id'], ['affaire.id'], name=op.f('fk_preavis_affaire_id_affaire')),
    sa.ForeignKeyConstraint(['decision'], ['preavis_decision.id'], name=op.f('fk_preavis_decision_preavis_decision')),
    sa.ForeignKeyConstraint(['preavis_id'], ['preavis_type.id'], name=op.f('fk_preavis_preavis_id_preavis_type')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_preavis_service_id_service')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preavis'))
    )
    op.create_table('relation_affaire_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('affaire_id', sa.Integer(), nullable=False),
    sa.Column('relation_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affaire_id'], ['affaire.id'], name=op.f('fk_relation_affaire_client_affaire_id_affaire')),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_relation_affaire_client_client_id_client')),
    sa.ForeignKeyConstraint(['relation_type_id'], ['relation_affaire_client_type.id'], name=op.f('fk_relation_affaire_client_relation_type_id_relation_affaire_client_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relation_affaire_client'))
    )
    op.drop_index('my_index', table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_models')
    )
    op.create_index('my_index', 'models', ['name'], unique=1)
    op.drop_table('relation_affaire_client')
    op.drop_table('preavis')
    op.drop_table('numero_relation')
    op.drop_table('numero_plan')
    op.drop_table('modification_affaire')
    op.drop_table('facture_partielle')
    op.drop_table('etape_affaire')
    op.drop_table('emoluments_rf')
    op.drop_table('affaire_numero')
    op.drop_table('remarque_affaire')
    op.drop_table('numero')
    op.drop_table('facture')
    op.drop_table('envoi_document')
    op.drop_table('client_personne')
    op.drop_table('client_entreprise')
    op.drop_table('affaire')
    op.drop_table('statut_affaire')
    op.drop_table('service')
    op.drop_table('remarque_preavis')
    op.drop_table('relation_type')
    op.drop_table('relation_affaire_client_type')
    op.drop_table('preavis_type')
    op.drop_table('preavis_decision')
    op.drop_table('plan')
    op.drop_table('operateur')
    op.drop_table('numero_type')
    op.drop_table('numero_etat')
    op.drop_table('modification_affaire_type')
    op.drop_table('emoluments_rf_parametres')
    op.drop_table('emoluments_mo_parametres')
    op.drop_table('emoluments_mo')
    op.drop_table('document')
    op.drop_table('constant')
    op.drop_table('client')
    op.drop_table('cadastre')
    op.drop_table('affaire_type')
    # ### end Alembic commands ###
